### ISSUE TITLE
E_WARNING: Undefined array key "page"

### ISSUE THREAD

**Issue by avbor** [rztuc/dokuwiki-plugin-authchained#16]
DokuWiki 2024-02-06b "Kaos" + chained auth plugin + php 8.3 = a lot of warnings in log:

```
2024-09-10 06:49:38
E_WARNING: Undefined array key "page"
/mnt/hdd1/www/wiki/lib/plugins/authchained/auth.php(446)
#0 /mnt/hdd1/www/wiki/lib/plugins/authchained/auth.php(446): dokuwiki\ErrorHandler::errorHandler()
#1 /mnt/hdd1/www/wiki/inc/auth.php(643): auth_plugin_authchained->cleanGroup()
#2 /mnt/hdd1/www/wiki/inc/auth.php(574): auth_isMember()
#3 /mnt/hdd1/www/wiki/inc/Extension/AdminPlugin.php(91): auth_ismanager()
#4 /mnt/hdd1/www/wiki/inc/Ui/Admin.php(137): dokuwiki\Extension\AdminPlugin->isAccessibleByCurrentUser()
#5 /mnt/hdd1/www/wiki/inc/Ui/Admin.php(32): dokuwiki\Ui\Admin->getPluginList()
#6 /mnt/hdd1/www/wiki/inc/template.php(208): dokuwiki\Ui\Admin->show()
#7 /mnt/hdd1/www/wiki/inc/Action/Admin.php(43): tpl_admin()
#8 /mnt/hdd1/www/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
#9 [internal function]: tpl_content_core()
#10 /mnt/hdd1/www/wiki/inc/Extension/Event.php(134): call_user_func_array()
#11 /mnt/hdd1/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#12 /mnt/hdd1/www/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
#13 /mnt/hdd1/www/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
#14 /mnt/hdd1/www/wiki/inc/actions.php(30): include('...')
#15 /mnt/hdd1/www/wiki/doku.php(131): act_dispatch()
#16 {main}

2024-09-10 06:49:38
E_WARNING: Undefined array key "page"
/mnt/hdd1/www/wiki/lib/plugins/authchained/auth.php(243)
#0 /mnt/hdd1/www/wiki/lib/plugins/authchained/auth.php(243): dokuwiki\ErrorHandler::errorHandler()
#1 /mnt/hdd1/www/wiki/inc/common.php(1698): auth_plugin_authchained->getUserData()
#2 /mnt/hdd1/www/wiki/inc/common.php(1646): userlink()
#3 /mnt/hdd1/www/wiki/inc/template.php(942): editorinfo()
#4 /mnt/hdd1/www/wiki/lib/tpl/dokuwiki/main.php(65): tpl_pageinfo()
#5 /mnt/hdd1/www/wiki/inc/actions.php(30): include('...')
#6 /mnt/hdd1/www/wiki/doku.php(131): act_dispatch()
#7 {main}
```

Is there any chance of fixing this?

**Comment by einhirn** [comment]
Fixed by #17
